//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunSite.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satislar
    {
        public byte SatisID { get; set; }
        public Nullable<byte> Urun { get; set; }
        public Nullable<byte> Personel { get; set; }
        public Nullable<byte> Musteri { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        public virtual Personeller Personeller { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
